apiVersion: v1
kind: Pod
metadata:
  name: test-pd
  labels:
    app: hello-world
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /Users/sudershan/Downloads/Kubernetes/hostpath
      # this field is optional
      type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nodeport
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30995
  selector:
      app: hello-world
  type: NodePort